import Loading from "@/components/loading";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import AuthProvider from "@/providers/auth-provider";
import TanstackQueryProvider from "@/providers/tanstack-query-provider";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `min-h-screen bg-background font-mulish antialiased`,
          mulish.variable,
        )}
      >
        <Suspense fallback={<Loading />}>
          <TanstackQueryProvider>
            <AuthProvider>{children}</AuthProvider>
          </TanstackQueryProvider>
          <Toaster />
        </Suspense>
      </body>
    </html>
  );
}
