import { AppSidebar } from "@/app/(admin)/admin/_components/app-sidebar";
import Loading from "@/components/loading";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Metadata } from "next";
import { PropsWithChildren, Suspense } from "react";
import Header from "./admin/_components/header";

export const metadata: Metadata = {
  title: "K-Shop Admin",
  description: "Generated by Kira",
};

const AdminLayout = ({ children }: PropsWithChildren) => {
  return (
    <Suspense fallback={<Loading />}>
      <SidebarProvider>
        <AppSidebar />
        <div className="flex w-full flex-col">
          <Header />
          <main className="w-full flex-1 p-4">
            <div>{children}</div>
          </main>
        </div>
      </SidebarProvider>
    </Suspense>
  );
};

export default AdminLayout;
