export const productData = [
  {
    id: "1",
    name: "Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation.",
    image: "https://example.com/images/wireless-headphones.jpg",
    slug: "wireless-headphones",
    price: 150,
    rating: 4.5,
    subcategory: {
      id: "101",
      name: "Audio Equipment",
      description: "Devices for high-quality sound experience.",
      image: "https://example.com/images/audio-equipment.jpg",
      slug: "audio-equipment",
    },
    isDelete: false,
    createdAt: "2024-10-31T14:16:42.842Z",
    updatedAt: "2024-10-31T14:16:42.842Z",
    deletedAt: null,
  },
  {
    id: "2",
    name: "Gaming Mouse",
    description: "Ergonomic gaming mouse with customizable buttons.",
    image: "https://example.com/images/gaming-mouse.jpg",
    slug: "gaming-mouse",
    price: 50,
    rating: 4.2,
    subcategory: {
      id: "102",
      name: "Computer Accessories",
      description: "Accessories for computers and gaming setups.",
      image: "https://example.com/images/computer-accessories.jpg",
      slug: "computer-accessories",
    },
    isDelete: true,
    createdAt: "2024-10-31T14:16:42.842Z",
    updatedAt: "2024-10-31T14:16:42.842Z",
    deletedAt: "2024-10-31T14:16:42.842Z",
  },
];
